name: publish

on:
  create:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Install
        run: yarn install
      - name: Update package version
        run: npm --no-git-tag-version version ${{ steps.previoustag.outputs.tag }}
      - name: Build
        run: yarn run build:npm
      # - name: Publish
      #   run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  create-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          name: github.ref
          bodyFile: 'docs/release/changelog-${{ steps.previoustag.outputs.tag }}.md'
          token: ${{ secrets.GITHUB_TOKEN }}
